# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'coffeescript', input: 'public/javascripts', output: 'public/javascripts/compiled'
guard 'coffeescript', input: 'spec/javascripts', output: 'spec/javascripts/compiled'
